spring:
  data:
    mongodb:
      uri: mongodb://admin_game:XMOJocgKlmRHz2O@localhost:27017/games?authSource=admin
      uuid-representation: standard
      
logging:
  pattern.console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

build:
  version: "1.0"

betsanddice-craps:
  message: "Welcome to Bets-And-Dice Craps local API "
